### ISSUE TITLE
Photography

### ISSUE THREAD

**Issue by kaythaney** [thaneyriordan/plan#1]
- [x] secure photographer contract, deposit
- [x] chat with kelcey about photo timing
- [x] let adderley know about family photos at venue
- [x] let family know about photo timing after ceremony
- [x] Pay photographer
- [ ] Get permit #19 

:camera: :+1:

**Comment by riordan** [comment]
Are we paying for her hotel down here?

**Comment by kaythaney** [comment]
travel costs are included in her contract. she asked for us to send her
hotel stuff, but that's above the $300 she's planning on. might want to
send a few options?

On Tue, Jan 12, 2016 at 5:44 PM, David Riordan notifications@github.com
wrote:

> Are we paying for her hotel down here?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/thaneyriordan/plan/issues/1#issuecomment-171085728.

## 

@kaythaney http://twitter.com/kaythaney/
@MozillaScience http://twitter.com/mozillascience

**Comment by kaythaney** [comment]
note: she's only staying 1 night.

On Tue, Jan 12, 2016 at 5:58 PM, Kaitlin Thaney kaitlin.thaney@gmail.com
wrote:

> travel costs are included in her contract. she asked for us to send her
> hotel stuff, but that's above the $300 she's planning on. might want to
> send a few options?
> 
> On Tue, Jan 12, 2016 at 5:44 PM, David Riordan notifications@github.com
> wrote:
> 
> > Are we paying for her hotel down here?
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/thaneyriordan/plan/issues/1#issuecomment-171085728.
> 
> ## 
> 
> @kaythaney http://twitter.com/kaythaney/
> @MozillaScience http://twitter.com/mozillascience

## 

@kaythaney http://twitter.com/kaythaney/
@MozillaScience http://twitter.com/mozillascience

**Comment by riordan** [comment]
Perfect.   

On 1/12/16 17:59, kaythaney wrote:

> note: she's only staying 1 night.
> 
> On Tue, Jan 12, 2016 at 5:58 PM, Kaitlin Thaney kaitlin.thaney@gmail.com
> wrote:
> 
> > travel costs are included in her contract. she asked for us to send her
> > hotel stuff, but that's above the $300 she's planning on. might want to
> > send a few options?
> > 
> > On Tue, Jan 12, 2016 at 5:44 PM, David Riordan notifications@github.com
> > wrote:
> > 
> > > Are we paying for her hotel down here?
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/thaneyriordan/plan/issues/1#issuecomment-171085728.
> > 
> > ## 
> > 
> > @kaythaney http://twitter.com/kaythaney/
> > @MozillaScience http://twitter.com/mozillascience
> 
> ## 
> 
> @kaythaney http://twitter.com/kaythaney/
> @MozillaScience http://twitter.com/mozillascience
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/thaneyriordan/plan/issues/1#issuecomment-171089594.

## 

-- <br />
David Riordan <br />
david.riordan@gmail.com | gpg 235D 9DC9 5EF6 277C <br />
@riordan | +1 (203)-521-1222 <br />

**Comment by riordan** [comment]
Photographer paid!

**Comment by kaythaney** [comment]
Note: still have 2 surveys / questionairres to fill out for her. On the docket to do this week.

**Comment by kaythaney** [comment]
1 survey left, need @riordan 's input (emailed to you.)
