### ISSUE TITLE
List of Critical Songs

### ISSUE THREAD

**Issue by riordan** [thaneyriordan/plan#10]
- **Processional**: Sigur Ros - [Hoppipolla](https://play.spotify.com/track/0nbAKsTcygTNGU5dxO6y8f)
- **First Dance**: Sarah Vaughan - [The More I see You](https://play.spotify.com/track/6avhQij1mq5nQFgfJchCNm) (Crazy He Calls Me)
- **Second Dance**: Otis Redding [Stand by Me](https://play.spotify.com/track/1aj4GXfmEYXfdVZohCpNKu)

**Comment by riordan** [comment]
@kaythaney: does this look complete?

**Comment by kaythaney** [comment]
yep! we should check on father/daughter + mother/son.

On Thu, Apr 14, 2016 at 7:56 AM, David Riordan notifications@github.com
wrote:

> Assigned #10 https://github.com/thaneyriordan/plan/issues/10 to
> @kaythaney https://github.com/kaythaney.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/thaneyriordan/plan/issues/10#event-627222911

## 

@kaythaney http://twitter.com/kaythaney/
@MozillaScience http://twitter.com/mozillascience

**Comment by kaythaney** [comment]
new order: sarah vaughan (first dance) -> parents' dance (KT and dad to start) to sam cooke song -> otis redding (open to all). 

still to do: relay that to the DJ.

**Comment by kaythaney** [comment]
Cake cutting: Sugar Pie, Honey Bunch.
