### ISSUE TITLE
Institute daily standup

### ISSUE THREAD

**Issue by riordan** [thaneyriordan/plan#16]
In order to keep momentum going on wedding issues before deadline.

**Comment by riordan** [comment]
7am standup time work for everyone?

**Comment by kaythaney** [comment]
works for me!

On Thu, Apr 14, 2016 at 11:26 AM, David Riordan notifications@github.com
wrote:

> 7am standup time work for everyone?
> 
> —
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub
> https://github.com/thaneyriordan/plan/issues/16#issuecomment-210002673

## 

@kaythaney http://twitter.com/kaythaney/
@MozillaScience http://twitter.com/mozillascience
