### ISSUE TITLE
Get NYC Photography permit

### ISSUE THREAD

**Issue by riordan** [thaneyriordan/plan#19]
Get permit for taking photos in Prospect Park

[NYC Parks permits](http://www.nycgovparks.org/permits/film-and-photo-guidelines)

**Comment by kaythaney** [comment]
Sent in an email to the nycpermits folks, no reply yet. thoughts, @riordan ? <shrugs>

**Comment by kaythaney** [comment]
left voicemail for the prospect park office: 7189658973

need to check and see whether we fall under this:  http://www.nycgovparks.org/rules/section-1-05 (where we would require a permit)
