### ISSUE TITLE
music / DJ

### ISSUE THREAD

**Issue by kaythaney** [thaneyriordan/plan#2]
:notes: 
- [x] figure out playlist, first dances, master of ceremonies
- [x] Identify DJ
- [x] List of critical songs (tracking on #10)
- [x] DJ Contract
- [x] DJ Survey
- [x] Pay DJ

**Comment by kaythaney** [comment]
@riordan - thoughts? have you chatted with brian at all?

**Comment by riordan** [comment]
Music to be handled by [DJ Dave Medina](http://www.djmedina.com/?v=mixes)

**Comment by riordan** [comment]
Pay by tomorrow

**Comment by kaythaney** [comment]
First deposit paid.

**Comment by kaythaney** [comment]
need to bring checks to the wedding. opening separate issue.
