### ISSUE TITLE
Hotel / housing

### ISSUE THREAD

**Issue by kaythaney** [thaneyriordan/plan#4]
:house: :hotel: :bride_with_veil: 
- [x] secure hotel block - @kaythaney, @riordan 
- [x] look at airbnbs closer to the venue for getting ready - @kaythaney

**Comment by riordan** [comment]
Do we want to get an AirBnb option list together?

**Comment by kaythaney** [comment]
i can, if you'd like. are we going to try to consolidate transport for
family, though? gets exponentially harder if we scatter people.

On Tue, Jan 12, 2016 at 5:43 PM, David Riordan notifications@github.com
wrote:

> Do we want to get an AirBnb option list together?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/thaneyriordan/plan/issues/4#issuecomment-171085463.

## 

@kaythaney http://twitter.com/kaythaney/
@MozillaScience http://twitter.com/mozillascience

**Comment by kaythaney** [comment]
do you know if your family is staying / grandma?

On Tue, Jan 12, 2016 at 5:59 PM, Kaitlin Thaney kaitlin.thaney@gmail.com
wrote:

> i can, if you'd like. are we going to try to consolidate transport for
> family, though? gets exponentially harder if we scatter people.
> 
> On Tue, Jan 12, 2016 at 5:43 PM, David Riordan notifications@github.com
> wrote:
> 
> > Do we want to get an AirBnb option list together?
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/thaneyriordan/plan/issues/4#issuecomment-171085463.
> 
> ## 
> 
> @kaythaney http://twitter.com/kaythaney/
> @MozillaScience http://twitter.com/mozillascience

## 

@kaythaney http://twitter.com/kaythaney/
@MozillaScience http://twitter.com/mozillascience

**Comment by riordan** [comment]
Not sure. I'll ask today though.

**Comment by kaythaney** [comment]
airbnb list: https://www.airbnb.com/wishlists/109734243  

care to get that up on the site when you have a chance?

**Comment by kaythaney** [comment]
nudge! can you get this up when you get a chance? @riordan
