### ISSUE TITLE
Swag

### ISSUE THREAD

**Issue by kaythaney** [thaneyriordan/plan#6]
- [x] boutonnieres, corsages for groomsmen + mothers [closed in favor of: #8]
- [x] party favors
- [x] wedding party gifts 
- [x] guestbook - MJT to bring _Joy of Cooking_
- [x] Thank Yous for Kristen & Aleks

**Comment by riordan** [comment]
Breaking some of this needs being broken out into its own issues.

**Comment by kaythaney** [comment]
Wedding party + parents + grandmother are sorted. 

Party favor design done. 

Present for Aleks and Kristen in the works.

**Comment by kaythaney** [comment]
Sorted!
