### ISSUE TITLE
After-party

### ISSUE THREAD

**Issue by kaythaney** [thaneyriordan/plan#7]
- [x] Pull together afterparty email blast
- [x] Update website with afterparty information
- [x] Write/Send afterparty email
- [ ] Tweet it.

Afterparty to be held at Greenwood Park, in Windsor Terrace

**Comment by riordan** [comment]
[Greenwood Park](http://greenwoodparkbk.com/blog/) - Free

**Comment by kaythaney** [comment]
Friends delegated to hold court?
